package vadimerenkov.autasker.core.presentation.theme
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable

val blue_lightScheme = lightColorScheme(
    primary = blue_primaryLight,
    onPrimary = blue_onPrimaryLight,
    primaryContainer = blue_primaryContainerLight,
    onPrimaryContainer = blue_onPrimaryContainerLight,
    secondary = blue_secondaryLight,
    onSecondary = blue_onSecondaryLight,
    secondaryContainer = blue_secondaryContainerLight,
    onSecondaryContainer = blue_onSecondaryContainerLight,
    tertiary = blue_tertiaryLight,
    onTertiary = blue_onTertiaryLight,
    tertiaryContainer = blue_tertiaryContainerLight,
    onTertiaryContainer = blue_onTertiaryContainerLight,
    error = blue_errorLight,
    onError = blue_onErrorLight,
    errorContainer = blue_errorContainerLight,
    onErrorContainer = blue_onErrorContainerLight,
    background = blue_backgroundLight,
    onBackground = blue_onBackgroundLight,
    surface = blue_surfaceLight,
    onSurface = blue_onSurfaceLight,
    surfaceVariant = blue_surfaceVariantLight,
    onSurfaceVariant = blue_onSurfaceVariantLight,
    outline = blue_outlineLight,
    outlineVariant = blue_outlineVariantLight,
    scrim = blue_scrimLight,
    inverseSurface = blue_inverseSurfaceLight,
    inverseOnSurface = blue_inverseOnSurfaceLight,
    inversePrimary = blue_inversePrimaryLight,
    surfaceDim = blue_surfaceDimLight,
    surfaceBright = blue_surfaceBrightLight,
    surfaceContainerLowest = blue_surfaceContainerLowestLight,
    surfaceContainerLow = blue_surfaceContainerLowLight,
    surfaceContainer = blue_surfaceContainerLight,
    surfaceContainerHigh = blue_surfaceContainerHighLight,
    surfaceContainerHighest = blue_surfaceContainerHighestLight,
)

val violet_lightScheme = lightColorScheme(
    primary = violet_primaryLight,
    onPrimary = violet_onPrimaryLight,
    primaryContainer = violet_primaryContainerLight,
    onPrimaryContainer = violet_onPrimaryContainerLight,
    secondary = violet_secondaryLight,
    onSecondary = violet_onSecondaryLight,
    secondaryContainer = violet_secondaryContainerLight,
    onSecondaryContainer = violet_onSecondaryContainerLight,
    tertiary = violet_tertiaryLight,
    onTertiary = violet_onTertiaryLight,
    tertiaryContainer = violet_tertiaryContainerLight,
    onTertiaryContainer = violet_onTertiaryContainerLight,
    error = violet_errorLight,
    onError = violet_onErrorLight,
    errorContainer = violet_errorContainerLight,
    onErrorContainer = violet_onErrorContainerLight,
    background = violet_backgroundLight,
    onBackground = violet_onBackgroundLight,
    surface = violet_surfaceLight,
    onSurface = violet_onSurfaceLight,
    surfaceVariant = violet_surfaceVariantLight,
    onSurfaceVariant = violet_onSurfaceVariantLight,
    outline = violet_outlineLight,
    outlineVariant = violet_outlineVariantLight,
    scrim = violet_scrimLight,
    inverseSurface = violet_inverseSurfaceLight,
    inverseOnSurface = violet_inverseOnSurfaceLight,
    inversePrimary = violet_inversePrimaryLight,
    surfaceDim = violet_surfaceDimLight,
    surfaceBright = violet_surfaceBrightLight,
    surfaceContainerLowest = violet_surfaceContainerLowestLight,
    surfaceContainerLow = violet_surfaceContainerLowLight,
    surfaceContainer = violet_surfaceContainerLight,
    surfaceContainerHigh = violet_surfaceContainerHighLight,
    surfaceContainerHighest = violet_surfaceContainerHighestLight,
)

val blue_darkScheme = darkColorScheme(
    primary = blue_primaryDark,
    onPrimary = blue_onPrimaryDark,
    primaryContainer = blue_primaryContainerDark,
    onPrimaryContainer = blue_onPrimaryContainerDark,
    onSecondary = blue_onSecondaryDark,
    secondary = blue_secondaryDark,
    secondaryContainer = blue_secondaryContainerDark,
    onSecondaryContainer = blue_onSecondaryContainerDark,
    tertiary = blue_tertiaryDark,
    onTertiary = blue_onTertiaryDark,
    tertiaryContainer = blue_tertiaryContainerDark,
    onTertiaryContainer = blue_onTertiaryContainerDark,
    error = blue_errorDark,
    onError = blue_onErrorDark,
    errorContainer = blue_errorContainerDark,
    onErrorContainer = blue_onErrorContainerDark,
    background = blue_backgroundDark,
    onBackground = blue_onBackgroundDark,
    surface = blue_surfaceDark,
    onSurface = blue_onSurfaceDark,
    surfaceVariant = blue_surfaceVariantDark,
    onSurfaceVariant = blue_onSurfaceVariantDark,
    outline = blue_outlineDark,
    outlineVariant = blue_outlineVariantDark,
    scrim = blue_scrimDark,
    inverseSurface = blue_inverseSurfaceDark,
    inverseOnSurface = blue_inverseOnSurfaceDark,
    inversePrimary = blue_inversePrimaryDark,
    surfaceDim = blue_surfaceDimDark,
    surfaceBright = blue_surfaceBrightDark,
    surfaceContainerLowest = blue_surfaceContainerLowestDark,
    surfaceContainerLow = blue_surfaceContainerLowDark,
    surfaceContainer = blue_surfaceContainerDark,
    surfaceContainerHigh = blue_surfaceContainerHighDark,
    surfaceContainerHighest = blue_surfaceContainerHighestDark,
)

val violet_darkScheme = darkColorScheme(
    primary = violet_primaryDark,
    onPrimary = violet_onPrimaryDark,
    primaryContainer = violet_primaryContainerDark,
    onPrimaryContainer = violet_onPrimaryContainerDark,
    onSecondary = violet_onSecondaryDark,
    secondary = violet_secondaryDark,
    secondaryContainer = violet_secondaryContainerDark,
    onSecondaryContainer = violet_onSecondaryContainerDark,
    tertiary = violet_tertiaryDark,
    onTertiary = violet_onTertiaryDark,
    tertiaryContainer = violet_tertiaryContainerDark,
    onTertiaryContainer = violet_onTertiaryContainerDark,
    error = violet_errorDark,
    onError = violet_onErrorDark,
    errorContainer = violet_errorContainerDark,
    onErrorContainer = violet_onErrorContainerDark,
    background = violet_backgroundDark,
    onBackground = violet_onBackgroundDark,
    surface = violet_surfaceDark,
    onSurface = violet_onSurfaceDark,
    surfaceVariant = violet_surfaceVariantDark,
    onSurfaceVariant = violet_onSurfaceVariantDark,
    outline = violet_outlineDark,
    outlineVariant = violet_outlineVariantDark,
    scrim = violet_scrimDark,
    inverseSurface = violet_inverseSurfaceDark,
    inverseOnSurface = violet_inverseOnSurfaceDark,
    inversePrimary = violet_inversePrimaryDark,
    surfaceDim = violet_surfaceDimDark,
    surfaceBright = violet_surfaceBrightDark,
    surfaceContainerLowest = violet_surfaceContainerLowestDark,
    surfaceContainerLow = violet_surfaceContainerLowDark,
    surfaceContainer = violet_surfaceContainerDark,
    surfaceContainerHigh = violet_surfaceContainerHighDark,
    surfaceContainerHighest = violet_surfaceContainerHighestDark,
)

/*
private val mediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val highContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val mediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val highContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)


 */
@Composable
fun AutaskerTheme(
    themeColor: ThemeColor = ThemeColor.BLUE,
    darkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit
) {
	val colorScheme = if (darkTheme) {
        when (themeColor) {
	        ThemeColor.VIOLET -> violet_darkScheme
	        ThemeColor.BLUE -> blue_darkScheme
        }
    } else {
        when (themeColor) {
	        ThemeColor.VIOLET -> violet_lightScheme
	        ThemeColor.BLUE -> blue_lightScheme
        }
    }
	MaterialTheme(
		colorScheme = colorScheme,
		typography = AppTypography,
		content = content
	)
}

